project:
  type: website
  output-dir: _site
  resources:
    - images/hendralogo.png

website:
  title: "Nor Hendra"
  navbar:
    background: light
    title: false
    logo: images/hendralogo.png
    logo-alt: "Hendra Logo"
    logo-href: "/"
    right:
      - text: ""
        href: https://github.com/norhendra
        icon: github           # ← bootstrap icon name
        target: "_blank"
      - text: ""
        href: https://linkedin.com/in/norhendra
        icon: linkedin         # ← bootstrap icon name
        target: "_blank"
      - text: ""
        href: contact.html
        icon: envelope
        target: "_blank"
    left:
    - text: "Academic Projects"
      menu:
        - text: "Digital Product Management"
          href: "projects/productmanagement/productmanagement.html"
        - text: "Visual Analytics"
          href: "projects/vaa/vaa.html"            
        - text: "Spreadsheet Modelling"
          href: "projects/spreadsheet/spreadsheet.html"
       
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

  